### ISSUE TITLE
Questions about Code Release for CXR-to-report Generation

### ISSUE THREAD

**Issue by AlonzoLeeeooo** [hyn2028/llm-cxr#10]
Hi @hyn2028 ,

Thank you for your amazing work! The idea is enlightening!
 I am curious about when will your code and pre-trained model weights for CXR-to-report generation be released? 

Best

**Comment by hyn2028** [comment]
Hello @AlonzoLeeeooo.

You can find all the necessary checkpoints and code to run the demo (including cxr-to-report task) in this repository. If you have any questions or need further assistance, feel free to ask. 

Thank you!

**Comment by AlonzoLeeeooo** [comment]
> Hello @AlonzoLeeeooo.
> 
> You can find all the necessary checkpoints and code to run the demo (including cxr-to-report task) in this repository. If you have any questions or need further assistance, feel free to ask.
> 
> Thank you!

Thank you for replying! Is it `decode_cxr_all.py`? Just want to make sure that I haven't got it wrong.

**Comment by hyn2028** [comment]
Please see README.md for a working demo. By referring to the three sections below, you can install Python dependencies, download model checkpoints, and run the demo.

1. https://github.com/hyn2028/llm-cxr?tab=readme-ov-file#install-dependencies
2. https://github.com/hyn2028/llm-cxr?tab=readme-ov-file#pretrained-models
3. https://github.com/hyn2028/llm-cxr?tab=readme-ov-file#interactive-demo-in-local-environment-using-gradio

Currently, the demo can only be run through a GUI in the Gradio environment.

**Comment by AlonzoLeeeooo** [comment]
> Please see README.md for a working demo. By referring to the three sections below, you can install Python dependencies, download model checkpoints, and run the demo.
> 
> 1. https://github.com/hyn2028/llm-cxr?tab=readme-ov-file#install-dependencies
> 2. https://github.com/hyn2028/llm-cxr?tab=readme-ov-file#pretrained-models
> 3. https://github.com/hyn2028/llm-cxr?tab=readme-ov-file#interactive-demo-in-local-environment-using-gradio
> 
> Currently, the demo can only be run through a GUI in the Gradio environment.

Got it. Thanks.
