### ISSUE TITLE
Questions about the Model Size of LLM

### ISSUE THREAD

**Issue by AlonzoLeeeooo** [hyn2028/llm-cxr#11]
Hi @hyn2028 ,

Thank you for your amazing work! The idea is enlightening!
I wonder what model size do you use in your approach? Is it a 7B LLaMA or 13B one? I cannot find any illustration in the paper. Please correct me if I have some misunderstanding.

Best

**Comment by hyn2028** [comment]
Hello @AlonzoLeeeooo,

The base model used is dolly-v2-3b, as specified in the paper. It has a total of 3B parameters.

**Comment by AlonzoLeeeooo** [comment]
> Hello @AlonzoLeeeooo,
> 
> The base model used is dolly-v2-3b, as specified in the paper. It has a total of 3B parameters.

Thanks for replying!
