### ISSUE TITLE
Two Stage Tuning

### ISSUE THREAD

**Issue by ChangeNext** [hyn2028/llm-cxr#12]
Hello, thank you for the wonderful project. 
I have a few questions. You mentioned that the training was conducted in two stages, and I'm curious if there is a significant difference in performance compared to not using this two-stage approach. 
Additionally, when dividing the data into two stages, you mentioned using a larger amount of higher volume of lower quality data and a higher-quality pruned dataset. 
I'm interested in understanding the criteria used to make this distinction. For example, did you make this judgment directly, or were there specific criteria involved?

**Comment by hyn2028** [comment]
Hi, @ChangeNext.

For the first question, please refer to the ablation study in supplementary materials section D of the paper. Compared to train only the stage2, there was a noticeable performance improvement in the stage1 training in advance. (Table 7,8,9)

For the second question, please refer to section 2.4.2 in the paper. For stage 1 training, the data used was the entire image from MIMIC-CXR and the finding & impression section of the report. For stage 2 training, only the PA&AP view for images and the impression section were used for the report, and the first image-report pair in time per patient was used.
 
Regarding the second question, we recognized that the paper's explanation regarding the stage 1 dataset may be somewhat lacking. Thanks for pointing this out.
