### ISSUE TITLE
Code for quantizing latent vector of MIMIC-CXR images

### ISSUE THREAD

**Issue by o0t1ng0o** [hyn2028/llm-cxr#3]
Hi, 
Thank you for sharing your code.
Can you provide the code for uantizing latent vector of MIMIC-CXR images?

thx!

**Comment by o0t1ng0o** [comment]
@hyn2028

**Comment by hyn2028** [comment]
I appreciate your interest in the project. We just added sample code for encoding and decoding and updated the README, see commit 7d2c39e743c1826166cb247836887cd17a8ae2b3.
