### ISSUE TITLE
Speed up the inference time

### ISSUE THREAD

**Issue by o0t1ng0o** [hyn2028/llm-cxr#4]
Hi @hyn2028,

I found that it takes about 5 seconds to evaluate each sample by using "generate_llmcxr.py".
The test set of MIMIC-CXR includes about 3k\~7k images.
It requires about 4\~9 hours to inference the whole test set.

Do we have other way to speed up the inference process?

**Comment by hyn2028** [comment]
Hello. We also took that much time in the generation process for testing.  This is because the structure of the model (LLM) is not a very efficient structure for image generation. I'm sorry I can't help. This is a limitation of the model.

**Comment by o0t1ng0o** [comment]
Oh. Iseeee.
Thank you for your reply.
