### ISSUE TITLE
Question about loading pretrained LLM models

### ISSUE THREAD

**Issue by huanggeng698** [hyn2028/llm-cxr#6]
Hello,@hyn2028 
I have download your pretrained LLM weights, but when i run the scripts "python generate_llmcxr.py 
--model_path ./weights/llmcxr_checkpoint-v3-1e+v2-2e.tar.gz", it shows the error that: huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/llm-cxr-main/weights/llmcxr_checkpoint-v3-1e+v2-2e.tar.gz'. Use `repo_type` argument if needed. 
Can you help me solve the problem?
Thanks in advance.

**Comment by hyn2028** [comment]
Hi there. Please unzip those files (```llmcxr_checkpoint-v3-1e+v2-2e.tar.gz```). For the path, you should specify the directory where it was unzipped (```--model_path ./weights/llmcxr_checkpoint-v3-1e+v2-2e```).

**Comment by huanggeng698** [comment]
Thanks a lot for your kind help! Your work are quite impressive!
