### ISSUE TITLE
ValueError: Tokenizer class GPTNeoXTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by leo726** [hyn2028/llm-cxr#8]
when I downloaded and loaded the LLM pretrained model, it showed that "ValueError: Tokenizer class GPTNeoXTokenizer does not exist or is not currently imported.", can you help me with this issue?

**Comment by leo726** [comment]
okay, I already sovled it, that's because my version of transformers is too low, so upgrade the transformers can solve it.

**Comment by hyn2028** [comment]
We are glad you solved the problem. For compatibility and reproducibility, we highly recommend using the provided dependencies of the conda virtual environment.
